Repository ath1s/Stully, pull requests merged in 2021-05, with the labels that each got.

#42 session gebruikt om delen van de website te beschermen
  classes/Posts.php
  index.php
  pages/comment.php
  pages/post.php
  pages/timeline.php
Labels: enhancement

#41 Status
  classes/Account.php
Labels: enhancement

#46 renamed Posts.php, added createPost and htmlSpecialCharArray function…
  classes/Post.php
  classes/Posts.php
  pages/comment.php
  pages/post.php
  pages/timeline.php
Labels: enhancement

#47 Werkende coffeecall (BETA)
  .gitignore
  classes/Account.php
  coffeecall/receiver/call.php
  coffeecall/receiver/receiver.js
  coffeecall/sender/call.php
  coffeecall/sender/sender.js
  coffeecall/server.js
  coffeecall/style.css
  package-lock.json
  package.json
  pages/status.php
  php/change_status.php
  server/start.sh
Labels: back-end, enhancement

#51 Pointsystem
  classes/Post.php
  classes/vote.php
  pages/post.php
  php/vote.php
Labels: back-end

#55 Call room volume 1
  classes/Account.php
  coffeecall/receiver/call.php
  coffeecall/sender/call.php
  php/redirect1.php
  php/redirect2.php
Labels: back-end

#56 Timeline functie
  assets/img/profile-placeholder.png
  coffeecall/sender/call.php
  pages/timeline.php
  styles/index.css
Labels: front-end

#58 Post CSS
  pages/post.php
  pages/timeline.php
  styles/index.css
  styles/post.css
Labels: front-end

#61 Delete and edit post
  classes/Post.php
  pages/post.php
  php/delete.php
  php/edit.php
Labels: back-end
