Repository ath1s/Stully, pull requests merged in 2021-04, with the labels that each got.

#21 Package json
  .gitignore
  package.json
Labels: front-end

#23 login class gemaakt
  classes/Login.php
Labels: back-end

#25 class naam verandert
  classes/Login.php
Labels: bug
